import type { CalculatorSlug } from "@/types/calculator";

export const calculatorKeywords: Record<CalculatorSlug, string[]> = {
  "ez-grader": [
    "easy grader",
    "ez grader",
    "grader",
    "quick grade",
    "grade calculator",
    "grading calculator",
    "class grade calculator",
    "my grade calculator",
    "grade percent calculator",
    "score calculator",
    "teacher grader",
    "quick grader",
    "grade calc",
  ],
  "test-grade-calculator": [
    "test grade calculator",
    "exam grade calculator",
    "exam calculator",
    "calculate test grades",
    "grade test calculator",
    "quiz grade calculator",
    "score out of",
  ],
  "weighted-grade-calculator": [
    "weighted grade calculator",
    "average grade calculator",
    "gradebook calculator",
    "course grade calculator",
    "overall grade calculator",
    "assignment grade calculator",
    "class grade calculator",
    "total grade calculator",
    "grade calculator with percentages",
    "grade book calculator",
  ],
  "final-grade-calculator": [
    "final grade calculator",
    "what do I need on my final",
    "what grade do i need on my final",
    "final exam calculator",
    "final exam grade calculator",
    "finals grade calculator",
    "grade calculator final",
    "final grade calculator college",
    "rogerhub final grade",
  ],
  "gpa-calculator": [
    "gpa calculator",
    "grade point average calculator",
    "calculate gpa",
    "semester gpa calculator",
    "unweighted gpa calculator",
    "calculate semester gpa",
    "term gpa",
  ],
  "cumulative-gpa-calculator": [
    "cumulative gpa calculator",
    "overall gpa calculator",
    "running gpa calculator",
    "transcript gpa",
  ],
  "weighted-gpa-calculator": [
    "weighted gpa calculator",
    "honors gpa calculator",
    "ap gpa calculator",
  ],
  "raise-gpa-calculator": [
    "raise gpa calculator",
    "how to raise gpa",
    "target gpa calculator",
  ],
  "high-school-gpa-calculator": [
    "high school gpa calculator",
    "hs gpa calculator",
    "semester gpa high school",
  ],
  "college-gpa-calculator": [
    "college gpa calculator",
    "university gpa calculator",
    "semester gpa college",
    "gpa calculator college",
  ],
  "percentage-to-letter-grade": [
    "percentage to letter grade",
    "percent to letter grade",
    "grade converter",
    "percentage grade calculator",
  ],
  "letter-grade-calculator": [
    "letter grade calculator",
    "letter grade to percentage",
    "letter to percent",
  ],
  "canvas-grade-calculator": [
    "canvas grade calculator",
    "canvas grader",
    "canvas lms grade",
    "canvas course grade",
    "canvas assignment groups",
    "canvas weighted grades",
  ],
  "eoc-grade-calculator": [
    "eoc calculator",
    "eoc grade calculator",
    "end of course calculator",
    "florida end of course",
  ],
  "degree-classification-calculator": [
    "degree classification calculator",
    "uk degree calculator",
    "2:1 calculator",
    "uk grade calculator",
    "mark calculator uk",
  ],
  "atar-calculator": ["atar calculator", "estimate atar", "australian atar"],
  "gcse-grade-calculator": ["gcse grade calculator", "gcse 9-1", "percentage to gcse grade"],
  "cgpa-to-percentage": [
    "cgpa to percentage",
    "cgpa to percentage india",
    "cgpa to percentage pakistan",
    "hec cgpa to percentage",
    "cbse cgpa to percentage",
  ],
  "percentage-to-cgpa": [
    "percentage to cgpa",
    "percent to cgpa",
    "marks to cgpa",
    "percentage to cgpa india",
  ],
  "sgpa-to-cgpa": [
    "sgpa to cgpa",
    "sgpa to cgpa calculator",
    "convert sgpa to cgpa",
    "how to calculate cgpa from sgpa",
  ],
  "cgpa-calculator": [
    "cgpa calculator",
    "sgpa calculator",
    "cgpa calculator india",
    "10 point cgpa calculator",
  ],
  "cgpa-to-gpa": [
    "cgpa to gpa",
    "10 to 4 gpa",
    "10 point to 4.0",
    "convert cgpa to gpa",
    "india cgpa to us gpa",
  ],
  "mcmaster-gpa-to-us-gpa": [
    "mcmaster gpa to us",
    "12 point gpa to 4.0",
    "mcmaster 12 point gpa",
    "canadian gpa to us gpa",
  ],
  "uk-degree-to-us-gpa-reference": [
    "uk gpa to us gpa",
    "uk degree to us gpa",
    "2:1 to gpa",
    "uk classification to 4.0",
  ],
};
